# https://wiki.hypr.land/Configuring/


source = /home/night/.config/hypr/env_vars.conf
source = /home/night/.config/hypr/display.conf

source = /home/night/.config/hypr/programs.conf
source = /home/night/.config/hypr/autostart.conf

source = /home/night/.config/hypr/inputs.conf
source = /home/night/.config/hypr/keybinds.conf

source = /home/night/.config/hypr/rules.conf
